spring:
  application:
    name: toou
  profiles:
    default: local

logging:
  config: classpath:log4j2.yml

decorator:
  datasource:
    p6spy:
      enable-logging: true  # P6Spy SQL 로그 활성화
      log-format: "%(currentTime) | conn=%(connectionId) - %(executionTime) ms | %(category) | %(sqlSingleLine)"  # SQL 실행 시간 포함. 1줄만 출력됨.

---

spring:
  config:
    activate:
      on-profile: local, prod
    import: classpath:application-private.yml