spring:
  application:
    name: toou
  profiles:
    default: local
  jackson:
    time-zone: Asia/Seoul  # JSON 직렬화 시 한국 시간대 사용

logging:
  level:
    root: INFO  # 로그 레벨 설정
    com.p6spy: DEBUG
  file:
    name: logs/http-and-query.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "{ \"timestamp\": \"%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}\", \"level\": \"%p\", \"thread\": \"%t\", \"logger\": \"%c{1}\", \"message\": \"%m\" }%n"


decorator:
  datasource:
    p6spy:
      enable-logging: true  # P6Spy SQL 로그 활성화
      log-format: "%(currentTime) | conn=%(connectionId) - %(executionTime) ms | %(category) | %(sqlSingleLine)"  # SQL 실행 시간 포함. 1줄만 출력됨.
---

spring:
  config:
    activate:
      on-profile: local, prod
    import: classpath:application-private.yml