spring:
  application:
    name: toou
  profiles:
    default: local
  jackson:
    time-zone: Asia/Seoul  # JSON 직렬화 시 한국 시간대 사용

logging:
  level:
    root: INFO  # 로그 레벨 설정

---
spring:
  config:
    activate:
      on-profile: local, prod
    import: classpath:application-private.yml